### ISSUE TITLE
not able to run wikiextrator.py

### ISSUE THREAD

**Issue by pavnesh-c** [NirantK/hindi2vec#11]
i am getting following error while running 
```!python wikiextractor/wikiextractor/WikiExtractor.py $filename -o data/wiki_extr --json --quiet```

result
```Traceback (most recent call last):
  File "wikiextractor/wikiextractor/WikiExtractor.py", line 62, in <module>
    from .extract import Extractor, ignoreTag
ModuleNotFoundError: No module named '__main__.extract'; '__main__' is not a package```

**Comment by pavnesh-c** [comment]
help required @NirantK

**Comment by NirantK** [comment]
This repository is no longer maintained @pc-beast. Please use iNLTK by @goru001 instead
