### ISSUE TITLE
how to use pretrained model for text classification

### ISSUE THREAD

**Issue by 008karan** [NirantK/hindi2vec#6]
Really appreciate your efforts. 
I am not getting how to use  pretrained model  for text classification.

**Comment by NirantK** [comment]
Hey @008karan, you can refer this [notebook](https://github.com/fastai/fastai/blob/master/courses/dl2/imdb.ipynb) 

The link above from [fastai](https://github.com/fastai/fastai/) covers how you can fine tune this language model and use it for text classification. 

You can also refer the Fast AI Course Video Lesson 4 here: [(link to timestamped video)](https://youtu.be/gbceqO8PpBg?t=1h23m30s)

**Comment by 008karan** [comment]
Hey @NirantK, I have gone through the notebook.
Things which I understood:
1. They are using wikitext103 LM for transfer learning. So I can use the pre-trained models provided by you in place of that.
**As there  5 pre-trained models, I am not getting which one to use.**
2. Is configuration of models is same as provided in notebook `em_sz,nh,nl = 400,1150,3`.
3. I need to replace source language model with the one provided by you and follow all the steps given in the notebook.
correct me if I am wrong? 
Again thanks for the great work!

**Comment by NirantK** [comment]
With respect to 3, The notebook is on how to create the language models.
Not on how to use them.

With respect to 2, yes, the parameters are as per what worked.

With respect to 1, use what works Karan.

**Comment by NirantK** [comment]
In the original notebook by fastai.

Or, you could wait - I'll add the examples for text classification based on
FastAI version1.0 in a few days.

**Comment by 008karan** [comment]
have you added any example?

**Comment by NirantK** [comment]
Not yet. I'm still working on a different project.

You can pickup from the FastAI course Lesson 4.

**Comment by 008karan** [comment]
I went through the lesson 4 notebook.
I got to know that vocab file (_TEXT.pkl_) and encoder _(adam_enc_) is required to do any classification task.
But there is embedding being used in between but not getting which one. They are just defining dimentions.
Also how to use hindi2vec embedding for classification
